"""Continuum — desktop plugin build step (D-SB-6).

The Hermes desktop-plugin runtime permits only three import specifiers:
``@hermes/plugin-sdk``, ``react`` and ``react/jsx-runtime``. The shipped
``desktop/plugin.js`` additionally imports the runtime-agnostic interaction
module (``./kanban-interaction.js``), which the runtime rejects.

This build step produces an SDK-pure copy of the desktop plugin with that
module's consumed exports inlined verbatim. It does NOT modify the repository
source: the canonical pure module (``desktop/kanban-interaction.js``) remains
the single source of truth that the Node behavioural / parity / drift tests
bind to. The inlined artifact is what gets written to the desktop-plugin
install location.

Usage::

    python3 build/desktop/plugin_build.py --out /path/to/install/plugin.js
    python3 build/desktop/plugin_build.py --check          # validate only

The transform is pure and deterministic: same inputs -> same output.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DESKTOP_DIR = Path(__file__).resolve().parent
BUILD_ROOT = DESKTOP_DIR.parent
PLUGIN_JS = DESKTOP_DIR / "plugin.js"
SHARED_JS = DESKTOP_DIR / "kanban-interaction.js"

SDK_ALLOWED = {"@hermes/plugin-sdk", "react", "react/jsx-runtime"}
ILLEGAL_IMPORT = "./kanban-interaction.js"

# The exports `plugin.js` actually consumes (the "one illegal import" D-SB-6 fixes).
CONSUMED = [
    "BOARD_COLUMNS", "NON_INBOX_PLACEMENTS", "COLUMN_LABELS",
    "buildAcceptToast", "buildAcceptActions", "buildFailureToast",
    "buildFailureActions", "buildUndoToast",
    "navigateRight", "navigateLeft", "navigateDown", "navigateUp",
    "navigateHome", "navigateEnd",
    "classifyKeyEvent", "closeMenuFocusTarget",
    "canDropOnColumn", "copyIdValue",
    "menuItemsFor", "menuInitialHighlight", "menuHighlightIndex", "menuActivate",
]


def _split_exports(shared_src: str) -> dict:
    """Map each top-level `export const|function NAME` to its source chunk."""
    chunks = {}
    for part in re.split(r"(?m)^export\s+", shared_src):
        m = re.match(r"(?:const|function)\s+([A-Za-z_$][\w$]*)", part)
        if m:
            chunks[m.group(1)] = part.rstrip() + "\n"
    return chunks


def import_specifiers(src: str) -> set:
    specs = set()
    for m in re.finditer(r"""^\s*import\s+(?:[^'"]*?\s+from\s+)?['"]([^'"]+)['"]""", src, re.MULTILINE):
        specs.add(m.group(1))
    return specs


def build_plugin(plugin_src: str, shared_src: str) -> str:
    """Return an SDK-pure plugin source with the consumed interaction exports inlined."""
    chunks = _split_exports(shared_src)
    missing = [n for n in CONSUMED if n not in chunks]
    if missing:
        raise ValueError("shared module is missing consumed export(s): " + ", ".join(missing))

    # Drop the illegal import line.
    kept = [l for l in plugin_src.split("\n") if ILLEGAL_IMPORT not in l or not l.strip().startswith("import")]
    plugin = "\n".join(kept)

    block = []
    for name in CONSUMED:
        block.append("// " + name + " (inlined from the shared pure module)")
        block.append(chunks[name].rstrip())
        block.append("")
    block = "\n".join(block).rstrip() + "\n"

    marker = "} from '@hermes/plugin-sdk'"
    if marker not in plugin:
        raise ValueError("expected plugin.js to import from '@hermes/plugin-sdk'")
    idx = plugin.index(marker) + len(marker)

    header = (
        "\n\n// ── Interaction primitives, inlined at build time (D-SB-6) ───────────────\n"
        "// The desktop-plugin runtime permits only '@hermes/plugin-sdk', 'react' and\n"
        "// 'react/jsx-runtime'. The runtime-agnostic helpers this file consumes are\n"
        "// inlined verbatim; behaviour is unchanged. Generated by\n"
        "// build/desktop/plugin_build.py — do not edit by hand.\n"
    )
    out = plugin[:idx] + header + block + plugin[idx:]

    illegal = import_specifiers(out) - SDK_ALLOWED
    if illegal:
        raise ValueError("build produced non-SDK imports: " + ", ".join(sorted(illegal)))
    return out


def _assert_sdk_pure(src: str) -> None:
    illegal = import_specifiers(src) - SDK_ALLOWED
    if illegal:
        raise SystemExit("not SDK-pure; unexpected imports: " + ", ".join(sorted(illegal)))
    if ILLEGAL_IMPORT in src and re.search(r"from\s+['\"]" + re.escape(ILLEGAL_IMPORT), src):
        raise SystemExit("still imports " + ILLEGAL_IMPORT)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="plugin_build", description="Build the SDK-pure desktop plugin.")
    ap.add_argument("--plugin", default=str(PLUGIN_JS))
    ap.add_argument("--shared", default=str(SHARED_JS))
    ap.add_argument("--out", help="write the SDK-pure plugin here")
    ap.add_argument("--check", action="store_true", help="build in memory and validate only")
    args = ap.parse_args(argv)

    plugin_src = Path(args.plugin).read_text(encoding="utf-8")
    shared_src = Path(args.shared).read_text(encoding="utf-8")
    out = build_plugin(plugin_src, shared_src)
    _assert_sdk_pure(out)

    if args.check and not args.out:
        print("SDK-pure: OK ({} lines)".format(len(out.split(chr(10)))))
        return 0
    if args.out:
        Path(args.out).write_text(out, encoding="utf-8")
        print("wrote SDK-pure plugin -> {}".format(args.out))
    else:
        sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
